### ISSUE TITLE
references ?

### ISSUE THREAD

**Issue by romainVala** [dicemt/DTI-NODDI#2]
Hello
thanks for providing the tools, we are very curious to know what is the theory behind the fact that you can fit noddi parameter from FA and MD map
Could you provide some references where I could learn more about the theory ?

Many thanks

**Comment by dicemt** [comment]
Sorry, I did not notice the issue is open!

I forgot to add the reference, but formulas are derived from:
Edwards LJ, Pine KJ, Ellerbrock I, Weiskopf N, Mohammadi S (2017) [NODDI-DTI: Estimating neurite orientation and dispersion parameters from a diffusion tensor in healthy white matter.](https://pubmed.ncbi.nlm.nih.gov/29326546/) Front Neurosci 11:720.
